### ISSUE TITLE
Support for WKT conversion

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-cove#1]
We'll need to decide how to handle Flatten Tool's WKT conversion option. That will be informed by the outcome of https://github.com/GFDRR/rdls-spreadsheet-template/issues/9 and https://github.com/OpenDataServices/flatten-tool/issues/429.

**Comment by duncandewhurst** [comment]
We are using WKT for geometries in the spreadsheet template so we'll need to set the wkt option in Flatten Tool's kwargs.

**Comment by radix0000** [comment]
Added "convert_wkt": True

**Comment by duncandewhurst** [comment]
Doesn't seem to be working when testing with [`wkt.xlsx`](https://github.com/GFDRR/rdls-cove/raw/test_data/test_data/wkt.xlsx):

Expected output, as returned by `flatten-tool unflatten -s schema/rdls_schema.json -m datasets -f xlsx --convert-wkt ../rdls-cove/test_data/wkt.xlsx`:

```json
{
    "datasets": [
        {
            "id": "1",
            "spatial": {
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [
                                30.0,
                                10.0
                            ],
                            [
                                40.0,
                                40.0
                            ],
                            [
                                20.0,
                                40.0
                            ],
                            [
                                10.0,
                                20.0
                            ],
                            [
                                30.0,
                                10.0
                            ]
                        ]
                    ]
                }
            }
        }
    ]
}
```

Actual output [from CoVE](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/data/55c91f09-2aeb-476b-a02d-55214b452238):

```json
{
  "datasets": [
    {
      "id": "1",
      "spatial": {}
    }
  ]
}
```

Resulting error:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/4e779bc5-afd9-4e90-8a07-0a99d6c41954)

**Comment by radix0000** [comment]
Was a flattentool version issue. Let me know if looks good now.

**Comment by duncandewhurst** [comment]
Looks good to me. Thanks!
