### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-cove#14]
From the scoping document:

"As a publisher, I need to access the conversion and validation online so that I don’t need to install software on my local machine."

A publicly accessible persistent URL via which users can access the tool.

What should the URL for the tool be? This should align with the chosen name.

[HTTPS://riskdatalibrary.org/toolkit](https://www.google.com/url?q=HTTPS://riskdatalibrary.org/toolkit&sa=D&source=docs&ust=1693219011282105&usg=AOvVaw2eMFq_FaOcNVmvOQbNdCqZ)

**Comment by stufraser1** [comment]
COVE Tool to be placed in domain riskdatalibrary.org


Documentation will be put at docs.riskdatalibrary.org
Toolkit.riskdatalibrary.org might need to point to multiple tools later, so the suggestion is **metadata.riskdatalibrary.org** pointing specifically to the cove tool.

@pzwsk do you agree and if so can you create this subdomain please?

**Comment by odscrachel** [comment]
Relates to https://github.com/GFDRR/rdl-standard/issues/226

**Comment by radix0000** [comment]
Note: Just clarify my understanding of where we are at. 

There will be two domains, **toolkit.riskdatalibrary.org** and  **metadata.riskdatalibrary.org** which will both point to **rdls.cove.opendataservices.coop** using CNAMEs. The **rdls.cove.opendataservices.coop** domain will then redirect to the live site (this has already been setup). Also note that **rdls.cove.opendataservices.coop** is not intended to work, in the sense that people can access the site directly using it. If used directly it will produce a 400 error, and only the riskdatalibrary.org domains/links should be distributed. The opendataservices.coop domain just exists so we don't have to give you an IP address and don't have to bother you if it changes.

**Comment by pzwsk** [comment]
Done

![image](https://github.com/GFDRR/rdls-cove/assets/2378439/ac0c05fc-6e45-457a-a4f0-9918f43f4cfd)

**Comment by pzwsk** [comment]
I will check in few min if it works and then close.

**Comment by pzwsk** [comment]
Here is what I get 

![image](https://github.com/GFDRR/rdls-cove/assets/2378439/6886df6a-1a68-415e-ad96-712db5f35d56)

**Comment by duncandewhurst** [comment]
I suspect that's because, whilst the redirect from rdls.cove.opendataservices.coop to the live server has been set up, the convertor hasn't actually been deployed to the server yet, which is why you're seeing the default nginx landing page. @radix0000 please confirm.

**Comment by duncandewhurst** [comment]
@radix0000, noting that only http://metadata.riskdatalibrary.org returns that page, whilst https://metadata.riskdatalibrary.org/ returns an 'unable to connect' error. Please make sure that the https URL is resolvable when the tool is deployed to the live server. Thanks!

**Comment by radix0000** [comment]
@pzwsk Thanks for setting up CNAMES. Looks to be all working. Have password protected for now (same as dev site).

Will setup SSL certificates etc. tomorrow.

**Comment by radix0000** [comment]
SSL certificate have now been added.

**Comment by duncandewhurst** [comment]
All of the following URLs are working for me so I'm going to close this issue.

http://metadata.riskdatalibrary.org
https://metadata.riskdatalibrary.org/
https://toolkit.riskdatalibrary.org/
https://toolkit.riskdatalibrary.org/
