### ISSUE TITLE
Legal compliance

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-cove#15]
From the scoping document:

"User tracking statement and privacy notice."

A privacy notice that complies with legal standards.

Are there existing terms of use and/or a privacy notice for RDLS to which the tool should link? @stufraser1 @matamadio I don't think we've established if there are existing terms of use or privacy notice to use?

**Comment by matamadio** [comment]
I am not aware of existing references.

**Comment by odscjen** [comment]
I found the GFDRR privacy policy https://www.gfdrr.org/en/privacy-policy and terms of use https://www.gfdrr.org/en/terms-of-use, I'm assuming we should use these and can just link to them?

**Comment by stufraser1** [comment]
> I found the GFDRR privacy policy https://www.gfdrr.org/en/privacy-policy and terms of use https://www.gfdrr.org/en/terms-of-use, I'm assuming we should use these and can just link to them?


Since we used those in the main website (https://riskdatalibrary.org/privacy and https://riskdatalibrary.org/terms), at the link below, it is appropriate to re-use here

**Comment by duncandewhurst** [comment]
These links have been added to the footer.
