### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-cove#17]
From the scoping document:

"A basic theme (colours, fonts, logos) that matches the palette and fonts from the RDLS documentation site."

From comments in document:

"I think we'll be using theme per original website [https://riskdatalibrary.org/](https://www.google.com/url?q=https://riskdatalibrary.org/&sa=D&source=docs&ust=1692961103592348&usg=AOvVaw26WW08Yjdg1aaS9Gn_pBKN) - fairly straightforward.
incl GFDRR logo (see footer)" @stufraser1

**Comment by odscrachel** [comment]
Still to add logo from footer https://riskdatalibrary.org/

**Comment by radix0000** [comment]
Logo added. Is size, location etc. okay?

**Comment by duncandewhurst** [comment]
Looks good to me :+1:

**Comment by stufraser1** [comment]
Location is good, Size is good.
However, the colours should be inverted please (white background black/dark blue text): https://disasterriskuk-my.sharepoint.com/:i:/g/personal/stuart_disaster-risk_uk/EcPEa_IfCgpAlXzw0jQ9WCoBhX38ylUqYrJU0jT7VawptQ?e=o9dQQu

OR place a banner across the bottom to show the logo in white on dark blue background, per riskdatalibrary.org:
<img width="1080" alt="image" src="https://github.com/GFDRR/rdls-cove/assets/12515042/124cf0a9-45eb-49cc-8f42-8e01c49ce61f">

**Comment by radix0000** [comment]
Logo is now in blue at bottom. Please check is okay.

**Comment by duncandewhurst** [comment]
Looks good to me :+1:

**Comment by stufraser1** [comment]
Thanks. From the landing page copy, the logo position now looks good. We're not allowed to change the colour of it though according to brand style guide, so the logo needs to be in black, sorry for any confusion.

Please update logo colour to black.
________________________________

**Comment by radix0000** [comment]
Logo changed to black.

**Comment by stufraser1** [comment]
Thank you - looks good now.
