### ISSUE TITLE
Validation error messages

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-cove#18]
From the scoping document:

"As a publisher, I need guidance on how to resolve the errors in my data so that I can fix them."

Error messages that provide sufficient information for the user to fix the problems with their data.

Initial draft of error messages in [RDLS validation error messages (#draft #shared)](https://docs.google.com/spreadsheets/d/1S7WifJvrG-iRAe5vJ6ABnPuV58TvYHqTkx5mnKEQcNM/edit#gid=0)

**Comment by duncandewhurst** [comment]
Let's update the IRI format error message to address the common case of omitting the scheme component of a URL:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/83d29090-1d9a-4e90-82c5-0d0743885203)

I suggest the following text:

> `url` is not an IRI. IRI values must be formatted according to [RFC3987](https://datatracker.ietf.org/doc/html/rfc3987). Check that webpage URLs begin with 'http' or 'https', e.g. http://www.example.com.

**Comment by duncandewhurst** [comment]
* Remove the `/[number]` placeholder from error messages relating to array items, e.g. the error message for the following data should read:

> `countries` does not match any code. `countries` must match a code from the codelist specified in the schema.

```json
{
  "datasets": [
    {
      "id": "1",
      "title": "Example dataset",
      "risk_data_type": "hazard",
      "publisher": {
        "name": "Example publisher",
        "url": "https://www.example.com"
      },
      "spatial": {
        "scale": "national",
        "countries": ["A", "B"]
      },
      "license": "commercial",
      "contact_point": {
        "name": "Example contact point",
        "email": "mail@example.com"
      },
      "creator": {
        "name": "Example creator",
        "email": "mail@example.com"
      },
      "resources": [
        {
          "id": "1",
          "title": "Example resource",
          "description": "A resource",
          "format": "geotiff",
          "url": "http://www.example.com"
        }
      ],
      "links": [
        {
          "href": "https://raw.githubusercontent.com/GFDRR/rdl-standard/0__2__0/schema/rdls_schema.json",
          "rel": "describedby"
        }
      ]
    }
  ]
}

```

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/db186f8e-33d6-418b-9948-ffdfc89e5104)

* Remove code formatting from 'Required field ' in missing required fields errors, e.g. the error message below should be formatted as follows:

> Required field `id` is missing...

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/4d120f58-4c39-473f-a12d-d7a9f714053b)

* Add missing closing bracket at the end of array type errors:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/db369e4d-0845-45f6-8e5e-30bd3946a2a6)

* Add an error message for incorrect email formats, e.g. the below error message should be:

> `email` is not an email address.

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/df77d2f8-220d-4a47-bf63-4d7bd8c53002)

* Implement the error message specified in the spreadsheet for invalid oneOf errors, e.g.

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/0c603265-7db7-42fd-a894-3222652f315f)

Should be:

> <strong><code>{{ errors.0.path_ending }}</code> is incorrectly formatted. It must be formatted as a date (<code>YYYY-MM-DD</code>), a year-month (<code>YYYY-MM</code>) or a year (<code>YYYY</code>).</strong>

* Implement the error message specified in the spreadsheet when `Link.rel` does not match the pattern, e.g.

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/accf33fe-c464-4bd4-af1a-3e6540aa18a1)

Should be:

> <strong><code>{{ errors.0.path_ending }}</code> does not match the regex <code>{{ errors.0.validator_value }}. With the exception of the first item in the <code>links</code> array, the value of <code>{{ errors.0.path_ending }}</code> must not be 'describedby'.</code></strong>

**Comment by duncandewhurst** [comment]
Noting that I wasn't able to test all of the validation errors as the schema used in the test instance needs updating (see #27). Once that is done, then the error messages need to be checked using the `all_errors.json` file from https://github.com/GFDRR/rdls-cove/issues/26.

**Comment by duncandewhurst** [comment]
I realised that we actually need two error messages relating to `links.rel` ([test data](https://github.com/GFDRR/rdls-cove/raw/test_data/test_data/all_errors.json)).

* When `.rel` of the first item in the `links` array does not equal 'describedby', the error message below should be updated as follows:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/681fd8f4-19f8-4964-b7f0-7bc032c5b6bd)

>  `rel` is not 'describedby'. The first item in the links array must be a link to the canonical URL of the RDLS JSON schema with relation type 'describedby'.

* When `.rel` of a subsequent item in the `links` array equals 'describedby', the error message below should be updated as follows:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/8b06e7a0-40d5-4f1a-9727-18dee21e1b62)

> `rel` is 'describedby'. With the exception of the first item in the links array, the value of `rel` must not be 'describedby'.

**Comment by duncandewhurst** [comment]
Remove the code formatting from the final closing bracket in the array format error message:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/02ccd2df-2f4d-41ab-86b4-373257cab4d9)

**Comment by radix0000** [comment]
Fix bracket and extra rel error message

**Comment by odscrachel** [comment]
Checked this and agree only things outstanding are the formatting of the final closing bracket and extra rel error message. Everything else has been addressed.

**Comment by radix0000** [comment]
Done.

**Comment by duncandewhurst** [comment]
The following error message still needs updating 
![image](https://github.com/GFDRR/rdls-cove/assets/19265814/9174947c-f309-42a5-86c6-b18db6bcf3db)

Per https://github.com/GFDRR/rdls-cove/issues/18#issuecomment-1704626102, it should read:

>  `rel` is not 'describedby'. The first item in the `links` array must be a link to the canonical URL of the RDLS JSON schema with relation type 'describedby'.

The other `rel` error message is fine:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/24911c91-08c4-490b-9abe-c6bb81e787da)

**Comment by radix0000** [comment]
rel message changed.

**Comment by duncandewhurst** [comment]
Can't test due to https://github.com/GFDRR/rdls-cove/issues/29

@odscrachel, once that issue is resolved, please can you test using the data in https://github.com/GFDRR/rdls-cove/issues/18#issuecomment-1704626102 - there should be two different messages as explained in that comment.

**Comment by odscrachel** [comment]
I checked this today, both messages are now correct
