### ISSUE TITLE
About RLDS text

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdls-cove#2]
Replace current text:

About RDLS
Disaster risk assessments are more important and more effective than ever, but common issues with risk data are beginning to limit their application. The RDL was launched to address those issues by developing tools and resources designed specifically for the needs of disaster risk experts and the assessments they perform.
The Risk Data Library Standard (RDLS) gives risk experts a single language to describe hazard, exposure, vulnerability and modelled loss datasets. It gives datasets an underlying consistency that makes them highly interoperable and easily read by both people and machines. The schema also contains labels for key metadata fields, making it easier to identify datasets without relying on external files or descriptions. Learn more at the [RDLS documentation website](https://docs.riskdatalibrary.org/).`

with new text:

About the RIsk Data Library Standard

The Risk Data Library Standard (RDLS) is an open data standard to make it easier to work with disaster and climate risk data. It provides a common description of the data used and produced in risk assessments, including hazard, exposure, vulnerability, and modelled loss, or impact, data.

The RDLS provides a unique way to create, store, exchange and use disaster different risk information together. It is at the core of the Risk Data Library, a suite of open-source tools to work with disaster and climate risk data.

Learn more at the [RDLS documentation website](https://rdl-standard.readthedocs.io/en/latest/).`

**Comment by radix0000** [comment]
Done, closing.
