### ISSUE TITLE
Results sharing

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-cove#23]
From the scoping document:

"As a publisher, I need to share the results of checking my data with others so that we can collaborate on resolving issues."

An option to share validation results via URL.

**Comment by duncandewhurst** [comment]
Feature seems to be missing or undocumented. Please add the section shown in the scoping document:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/457b0c96-bf1c-44a5-aa2a-076ca3329bc6)

**Comment by radix0000** [comment]
Have added section.

**Comment by duncandewhurst** [comment]
Feature looks good to me :+1:

**Comment by radix0000** [comment]
Closing as done.
