### ISSUE TITLE
feedback / issues / contact

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdls-cove#24]
If users are having issues or need to request assistance, can we add a contact page, e.g., 
https://riskdatalibrary.org/contact
and point them to github  to leave any issues?

**Comment by duncandewhurst** [comment]
Suggest linking to https://docs.riskdatalibrary.org/en/dev/about/contacts/ instead as that page has more information on it. @stufraser1 sound good?

(Noting that we'll need to use https://docs.riskdatalibrary.org/en/latest/about/contacts/)

**Comment by stufraser1** [comment]
Wouldn't we link to docs.riskdatalibrary.org

Which in turn links to rtd...io/en/latest...?
________________________________

**Comment by duncandewhurst** [comment]
Actually, I think this issue is addressed by the revised landing page copy in https://github.com/GFDRR/rdls-cove/issues/21#issuecomment-1705727975, which includes the following paragraph:

> 
> ## Support and feedback
> 
> Need help with publishing RDLS metadata? Contact a member of the Risk Data Library team: [contact@riskdatalibrary.org](mailto:contact@riskdatalibrary.org)
> 
> To submit feedback on the RDLS Convertor or to report a bug, [open a GitHub issue](https://github.com/GFDRR/rdls-cove/issues/new/choose).

Feel free to reopen if you think otherwise!
