### ISSUE TITLE
Crash when data does not include a top-level datasets array

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-cove#25]
Input:

```json
{
  "test": {}
}
```

Output:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/a8949f05-5b3e-4ec6-91eb-ca53fc0c80c4)

**Comment by radix0000** [comment]
Now reporting more informative error.

**Comment by duncandewhurst** [comment]
There's a typo in the error message (datsets -> datasets):

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/285b9a31-b899-41d3-8110-0e9fd58126dd)

Can we also update it to explain the likely cause of the issue:

> Required field `datasets` is missing. Check that your metadata is provided in an [RDLS metadata package](https://docs.riskdatalibrary.org/en/dev/reference/package_schema/).

(Noting that's a link to the `dev` branch, it will need updating once 0__2__0 is released)

**Comment by odscrachel** [comment]
Typo fixed, just link to update

**Comment by duncandewhurst** [comment]
Looks good to me :+1:

Updating the link is covered by https://github.com/GFDRR/rdls-cove/issues/28 so I'll close this issue.
