### ISSUE TITLE
Update schema

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-cove#27]
@radix0000 please could you update the schema in the test instance to the latest version from the `dev` branch of the standard repo. the current version in the test instance seems quite out of date, which is making it difficult to test fully.

**Comment by radix0000** [comment]
Have updated schema.

**Comment by duncandewhurst** [comment]
Thanks! I've re-run [`all_errors.json`](https://github.com/GFDRR/rdls-cove/raw/test_data/test_data/all_errors.json) through the tool and updated the validation errors and validation error message issues.
