### ISSUE TITLE
Update links to point to /latest/

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-cove#28]
Once 0.2 is released, we'll need to update any URLs that point to the `dev` branch to point to `latest`.

At the same time, we can replace any links that point to https://rdl-standard.readthedocs.io/ with the new docs URL https://docs.riskdatalibrary.org/.

**Comment by radix0000** [comment]
Do let me know as soon as 0.2 is released, as there are whole series of checks and updates that are needed once it is released, which will take time.

**Comment by duncandewhurst** [comment]
There were some last-minute schema changes that delayed the release. See https://github.com/GFDRR/rdl-standard/issues/250 for the current status and remaining steps.

**Comment by duncandewhurst** [comment]
0.2.0 is released.

**Comment by duncandewhurst** [comment]
@radix0000 once the links are updated, please remove the password authentication from https://metadata.riskdatalibrary.org/ and https://toolkit.riskdatalibrary.org/. Thanks!

**Comment by radix0000** [comment]
Done and closing.
