### ISSUE TITLE
Stuck on 'your data is queued for processing'

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-cove#29]
To reproduce, submit data to https://metadata.riskdatalibrary.org in any format and via any upload method.

The tool gets stuck on the following message

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/4dd3d26e-cdfd-492e-853a-1a99674e3e60)

**Comment by radix0000** [comment]
Last night's server upgrades seem to have killed the background worker. Restarted. Working for me now, but let me know if there are still issues.
