### ISSUE TITLE
change reference to BODS

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdls-cove#3]
change references to 'BODS' to 'RDLS'? x3

Suggest new text for this top panel 'using the data review tool':

Use one of the links below to check that your data complies with the [Risk Data Library Standard](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) (RDLS).

    Upload an RDLS metadata file;
    Link to RDLS metadata on the web using a URL; or
    Paste in your RDLS JSON metadata

After submitting your metadata, use the information provided on the Results page to [check and review](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) the data’s quality and compliance with RDLS. Your data can also be downloaded in alternative RDLS-compliant formats from the Results page.

**Comment by radix0000** [comment]
Done, closing.
