### ISSUE TITLE
change BODS reference - Checking and reviewing your data

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdls-cove#5]
Replace text in panel 'Checking and reviewing your data':
"    Additional checks. A list of BODS-specific problems in the data."
with:
"    Additional checks. A list of RDLS-specific problems in the data."

**Comment by duncandewhurst** [comment]
Per the scoping document, we aren't implementing additional checks as part of the initial development so this text should be removed.

**Comment by radix0000** [comment]
Done, closing.
