### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdls-cove#6]
Spanish page uses English text. Will this be retained in final version with Spanish translation?
Could French be included too?

**Comment by duncandewhurst** [comment]
@stufraser1 translations aren't in scope for the initial development, though it is definitely something we could do in a future sprint. 

@radix0000 looks like the language switcher button has been carried over from BODS CoVE. Please remove it.

**Comment by radix0000** [comment]
Done, closing.
