### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-cove#9]
From original scoping:
"As a data publisher, I need to get feedback on the validity of my data against the RDLS schema so that I can correct errors."

Tables of validation errors grouped by type (e.g. missing required fields, format errors, other errors) with sufficient information for the user to identify and fix the problems with their data. See also [validation error messages](https://docs.google.com/document/d/1CFAaRijJ88kVYWkkd1-yibIUc7DzL6__lwBOP19eQn4/edit#heading=h.qm4bkmbm951).

Error messages that provide sufficient information for the user to fix the problems with their data.

----------------------------------------------------

I've drafted new and [updated error messages](https://docs.google.com/spreadsheets/d/1S7WifJvrG-iRAe5vJ6ABnPuV58TvYHqTkx5mnKEQcNM/edit#gid=0) for each validation keyword, type and format that is used in the RDLS schema.

@radix0000 please update the error messages and logic in https://github.com/GFDRR/rdls-cove/blob/main/cove_rdls/templates/cove_rdls/validation_table.html per the 'RDLS CoVE error description' column. Let me know if anything is unclear.

There might be one more error message to draft for the `prefixItems` keyword, but https://github.com/GFDRR/rdls-cove/issues/8 needs to be resolved before I can check.

**Comment by duncandewhurst** [comment]
Some feedback:

* Identical error messages are not grouped, e.g. the following test data should return one error message with an error count of 2 rather than two separate messages:

```json
{
  "datasets": [
    {
      "id": "1",
      "title": "Example dataset",
      "risk_data_type": "hazard",
      "publisher": {
        "name": "Example publisher",
        "url": "https://www.example.com"
      },
      "spatial": {
        "scale": "national"
      },
      "license": "commercial",
      "contact_point": {
        "name": "Example contact point",
        "email": "mail@example.com"
      },
      "creator": {
        "name": "Example creator",
        "email": "mail@example.com"
      },
      "resources": [
        {
          "id": "1",
          "title": "Example resource",
          "description": "A resource",
          "format": "geotiff",
          "url": "http://www.example.com"
        },
        {
          "id": 1,
          "title": "Example resource",
          "description": "A resource",
          "format": "geotiff",
          "url": "http://www.example.com"
        },
        {
          "id": 2,
          "title": "Example resource",
          "description": "A resource",
          "format": "geotiff",
          "url": "http://www.example.com"
        }
      ],
      "links": [
        {
          "href": "https://raw.githubusercontent.com/GFDRR/rdl-standard/0__2__0/schema/rdls_schema.json",
          "rel": "describedby"
        }
      ]
    }
  ]
}

```
![image](https://github.com/GFDRR/rdls-cove/assets/19265814/96590048-8bf9-4bc0-b88b-1b33e18dd252)

* Errors are not grouped by type (required fields, format errors, other errors) - can we add that? ([Example from OCDS DRT](https://review.standard.open-contracting.org/data/1c105fc1-6b9c-40ef-bf3f-10b5c533c8dd))
* Update column headers for clarity and to use title case consistently:
  * First 3 Examples -> First 3 Values
  * Location of first 3 errors > First 3 Locations
* When a value is a string, wrap it in quotes. Otherwise, it isn't possible to distinguish between strings and numbers, e.g. the error below would be easier to comprehend if the value (90) was wrapped in quotes to show that it is a string, not a number:

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/3d92b94c-8425-4444-aac2-8a6b75d4b090)

* Replace the '!' at the end of the 'There were no validation errors' with a period.
* Report the correct error count for empty objects, e.g. the following error should have an error count of 1 when `datasets/creator` is an empty object (`{}`)

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/07fffb09-a8d3-4909-bb19-8d26d869d57c)

* Populate the first 3 examples column for empty object errors, e.g. for the above error the examples column should contain `{}`

**Comment by duncandewhurst** [comment]
I've updated my previous comment with some additional feedback.

**Comment by duncandewhurst** [comment]
* Remove the 'First 3 errors column' from the Structural Errors - Required Fields box (it should always be blank, but presently it is populated when the parent object is empty, but not otherwise) ([test data](https://github.com/GFDRR/rdls-cove/raw/test_data/test_data/all_errors.json)):

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/22c2b4f4-f122-43a6-b626-8d4521b5329c)

* Now that the error messages are grouped, instead of repeating the guidance for resolving missing required fields for each missing field, we can move the "Your data must contain the required fields specified in the schema. Check that the field is present and not misspelt." sentence above the error table (after "Some or all of your data is missing fields which are required by the RDLS schema.") ([test data](https://github.com/GFDRR/rdls-cove/raw/test_data/test_data/all_errors.json)).

**Comment by radix0000** [comment]
Think done but needs checking.

**Comment by duncandewhurst** [comment]
Looks good. Two final minor nitpicks:

1. Now there are fewer columns in the required fields table, it looks a bit weird with right-aligned values in the Error Count column. Can we left align the error count values in all of the error tables?

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/61524563-e873-4a0f-a756-c21e55c84b85)

1. Can we update the sentence in at the start of the missing required fields box to read "Check that each field...." rather than "Check that the field...".

**Comment by radix0000** [comment]
Done.

**Comment by duncandewhurst** [comment]
Looks good to me :+1:
